<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $reportData['meta']['title'] }} - View | OwnStore PRO</title>

    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">

    <style>
        /* Print Optimization */
        @media print {
            body {
                background: white;
            }

            .no-print {
                display: none !important;
            }

            .print-container {
                box-shadow: none;
                border: none;
                margin: 0;
                padding: 0;
                width: 100%;
                max-width: 100%;
            }

            @page {
                margin: 1cm;
            }
        }
    </style>
</head>

<body class="bg-gray-100 font-sans text-gray-800 flex flex-col items-center min-h-screen p-8">

    <div class="no-print fixed top-6 z-50 bg-gray-900 text-white rounded-full px-6 py-3 shadow-2xl flex items-center gap-6">
        <a href="/reports" class="hover:text-teal-400 transition" title="Back"><i class="fas fa-arrow-left"></i></a>
        <div class="h-4 w-px bg-gray-600"></div>
        <button onclick="window.print()" class="hover:text-teal-400 transition font-bold" title="Print"><i class="fas fa-print mr-2"></i> Print</button>
        <button class="hover:text-teal-400 transition font-bold" title="Save PDF"><i class="fas fa-file-pdf mr-2"></i> PDF</button>
        <button class="hover:text-green-400 transition font-bold" title="Export Excel"><i class="fas fa-file-excel mr-2"></i> Excel</button>
    </div>

    <div class="print-container bg-white w-full max-w-[210mm] min-h-[297mm] shadow-xl p-12 relative mt-16 print:mt-0">

        <div class="border-b-2 border-teal-600 pb-6 mb-6">
            <div class="flex justify-between items-start">
                <div>
                    <h1 class="text-3xl font-extrabold text-teal-800 uppercase tracking-tight">{{ $reportData['company']['name'] }}</h1>
                    <p class="text-gray-500 text-sm mt-1">{{ $reportData['company']['address'] }}</p>
                    <p class="text-gray-500 text-sm"><i class="fas fa-phone-alt text-teal-600 text-xs mr-1"></i> {{ $reportData['company']['phone'] }}</p>
                </div>
                <div class="text-right">
                    <h2 class="text-xl font-bold text-gray-800">{{ $reportData['meta']['title'] }}</h2>
                    <span class="inline-block bg-teal-100 text-teal-800 text-xs font-bold px-2 py-1 rounded mt-2">
                        {{ $reportData['meta']['period'] }}
                    </span>
                </div>
            </div>
        </div>

        <div class="flex justify-between text-xs text-gray-500 mb-6 uppercase tracking-wider font-semibold">
            <span>Generated By: {{ $reportData['meta']['generated_by'] }}</span>
            <span>Date: {{ $reportData['meta']['generated_at'] }}</span>
        </div>

        <div class="overflow-hidden border border-gray-200 rounded-lg mb-8">
            <table class="w-full text-left border-collapse text-sm">
                <thead>
                    <tr class="bg-teal-700 text-white">
                        @foreach($reportData['columns'] as $col)
                        <th class="p-3 font-bold border-r border-teal-600 last:border-0">{{ $col }}</th>
                        @endforeach
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-100">
                    @foreach($reportData['rows'] as $index => $row)
                    <tr class="{{ $index % 2 == 0 ? 'bg-white' : 'bg-gray-50' }}">
                        @foreach($row as $cell)
                        <td class="p-3 border-r border-gray-100 last:border-0 font-mono text-gray-700">
                            {{ $cell }}
                        </td>
                        @endforeach
                    </tr>
                    @endforeach
                </tbody>
                @if(!empty($reportData['totals']))
                <tfoot>
                    <tr class="bg-gray-100 font-bold border-t-2 border-gray-300">
                        @foreach($reportData['totals'] as $total)
                        <td class="p-3 text-gray-900 border-r border-gray-200 last:border-0">
                            {{ $total }}
                        </td>
                        @endforeach
                    </tr>
                </tfoot>
                @endif
            </table>
        </div>

        <div class="mt-12 pt-6 border-t border-gray-200 text-center">
            <p class="text-xs text-gray-400 italic">This is a system generated report. No signature required.</p>
            <p class="text-[10px] text-gray-300 mt-1 uppercase">Powered by OwnStore PRO</p>
        </div>

    </div>

</body>

</html>