<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adjustment #{{ $adjustment->adjustment_no }}</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 14px;
            max-width: 800px;
            margin: 0 auto;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #ccc;
            padding-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            color: #000;
        }

        .details {
            margin-bottom: 30px;
            display: flex;
            justify-content: space-between;
        }

        .details-col {
            width: 48%;
        }

        .label {
            font-weight: bold;
            font-size: 12px;
            color: #666;
            text-transform: uppercase;
        }

        .value {
            font-size: 16px;
            margin-bottom: 10px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }

        th {
            background: #f0f0f0;
            text-align: left;
            padding: 8px;
            border-bottom: 2px solid #000;
            font-size: 12px;
            font-weight: bold;
            text-transform: uppercase;
        }

        td {
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .font-bold {
            font-weight: bold;
        }

        .text-red {
            color: #d32f2f;
        }

        .text-green {
            color: #388e3c;
        }

        .signatures {
            margin-top: 50px;
            display: flex;
            justify-content: space-between;
        }

        .sig-box {
            width: 40%;
            border-top: 1px solid #000;
            padding-top: 10px;
            text-align: center;
            font-weight: bold;
        }

        @media print {
            .no-print {
                display: none;
            }

            body {
                max-width: 100%;
                margin: 20px;
            }
        }

        .btn {
            background: #00bcd4;
            color: white;
            padding: 10px 20px;
            text-decoration: none;
            font-weight: bold;
            border-radius: 5px;
            display: inline-block;
            margin-bottom: 20px;
        }
    </style>
</head>

<body>

    <a href="#" onclick="window.print()" class="btn no-print">PRINT REPORT</a>

    <div class="header">
        <h1>STOCK ADJUSTMENT REPORT</h1>
        <div style="font-size: 12px; margin-top: 5px;">Generated by OwnStore PRO</div>
    </div>

    <div class="details">
        <div class="details-col">
            <div class="label">Adjustment No</div>
            <div class="value">{{ $adjustment->adjustment_no }}</div>

            <div class="label">Reason / Description</div>
            <div class="value">{{ $adjustment->description ?? '-' }}</div>
        </div>
        <div class="details-col text-right">
            <div class="label">Date</div>
            <div class="value">{{ $adjustment->adjustment_date }}</div>

            <div class="label">Type</div>
            <div class="value">{{ $adjustment->type }}</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 50px;">#</th>
                <th>Item Name</th>
                <th class="text-center">System Qty</th>
                <th class="text-center">Actual Qty</th>
                <th class="text-center">Diff</th>
            </tr>
        </thead>
        <tbody>
            @foreach($adjustment->items as $index => $item)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $item->item_name }}</td>
                <td class="text-center">{{ $item->system_stock }}</td>
                <td class="text-center font-bold">{{ $item->physical_stock }}</td>
                <td class="text-center font-bold {{ $item->difference < 0 ? 'text-red' : ($item->difference > 0 ? 'text-green' : '') }}">
                    {{ $item->difference > 0 ? '+' : '' }}{{ $item->difference }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="signatures">
        <div class="sig-box">
            Audited By
        </div>
        <div class="sig-box">
            Authorized By
        </div>
    </div>

</body>

</html>